spring.application.name=Personal_Financial_MGT
spring.datasource.url=jdbc:postgresql://localhost:5433/
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# Log file
logging.file.name=
# Log pattern (console)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg%n
# Log pattern (file)
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

#Jwt Configuration
Jwt_expirationTimeAccessToken =3600
Jwt_expirationTimeRefreshToken=180000
jwt_secretKey =05e50d0cc1344268138bb507883c0968578e8f191667f37297fe90cca9b47c0f
Jwt_header ='/authorization'
Jwt_url ='Authorization'
Jwt_prefix = 'Bearer'
spring.main.allow-circular-references=true

#File upload configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=5MB
server.address=
client.address=
file.allowed.extensions=jpg,jpeg,png,pdf